export const initialCards = [
  {
    id: 1,
    title: 'Linea POH & LXP',
    category: 'end',
    href: '/linea',
    icon: '📊',
    thumbnail: '/thumbnails/linea.jpg',
    size: 'wide',
  },
  {
    id: 2,
    title: 'Monad Mass Send',
    category: 'end',
    href: '/monad-send',
    icon: '🚀',
    thumbnail: '/thumbnails/monad.jpg',
    size: 'normal',
  },
  {
    id: 3,
    title: 'APR & APY Calculator',
    category: 'live',
    href: '/apr-apy-calculator',
    icon: '🧮',
    thumbnail: '/thumbnails/calculator.jpg',
    size: 'tall',
  },
  {
    id: 4,
    title: 'Resolv Points Checker',
    category: 'end',
    href: '/resolv',
    icon: '🔗',
    thumbnail: '/thumbnails/resolv.jpg',
    size: 'normal',
  },
  {
    id: 5,
    title: 'MCAP & FDV Calculator',
    category: 'live',
    href: '/mcap-fdv-calculator',
    icon: '📈',
    thumbnail: '/thumbnails/mcap.jpg',
    size: 'normal',
  },
  {
    id: 6,
    title: 'Randomizer Anime',
    category: 'live',
    href: '/randomizer-anime',
    icon: '🎲',
    thumbnail: '/thumbnails/anime.jpg',
    size: 'large',
  },
  {
    id: 7,
    title: 'Nillion Wallet',
    category: 'end',
    href: '/nillion',
    icon: '💰',
    thumbnail: '/thumbnails/nillion.jpg',
    size: 'tall',
  },
  {
    id: 8,
    title: 'Gensyn Check',
    category: 'end',
    href: '/gensyn',
    icon: '⚙️',
    thumbnail: '/thumbnails/gensyn.jpg',
    size: 'normal',
  },
  {
    id: 9,
    title: 'Shamir Secret Sharing',
    category: 'live',
    href: '/sss',
    icon: '🔐',
    thumbnail: '/thumbnails/sss.jpg',
    size: 'normal',
  },
  {
    id: 10,
    title: 'Illustration Challenge',
    category: 'live',
    href: '/illustration-challange',
    icon: '🎨',
    thumbnail: '/thumbnails/illustration.jpg',
    size: 'wide',
  },
  {
    id: 11,
    title: 'Base Learn',
    category: 'live',
    href: '/base-learn',
    icon: '📚',
    thumbnail: '/thumbnails/base.jpg',
    size: 'normal',
  },
  {
    id: 12,
    title: '100 Seconds',
    category: 'live',
    href: '/100-seconds',
    icon: '⏱️',
    thumbnail: '/thumbnails/100s.jpg',
    size: 'tall',
  },
  {
    id: 13,
    title: 'Countdown Timer',
    category: 'live',
    href: '/countdown',
    icon: '⏳',
    thumbnail: '/thumbnails/countdown.jpg',
    size: 'wide',
  },
  {
    id: 14,
    title: 'WA Contactless',
    category: 'live',
    href: '/wa-contactless',
    icon: '📱',
    thumbnail: '/thumbnails/wa-contactless.jpg',
    size: 'normal',
  },
];
